wp-graphql/wpgraphql-acf

.github/workflows/upload-schema-artifact.yml

- Change `docker-compose start app` to `docker-compose run app`
What currently open issues does this close or contribute?
closes #32 
This is hard to say for sure if it works without publishing a release. Running the commands locally appear to resolve the issue, but hard to fully reproduce the Github workflow environment.

fix: failing workflow to upload GraphQL Schema artifact upon releases

---

src/AcfGraphQLFieldType.php

When creating a new acf field in a field group that already has fields, the `graphql_description` field was defaulting to the value of the first field in the group. 
closes #70 
When adding a new field, we see the "GraphQL Description" inherits the value from the first field:
Now "GraphQL Description"  is a blank value when a new field is added:

fix: graphql_description default value incorrect

---

src/Admin/Settings.php

This replaces the `filter_input` function with `sanitize_text_field` when verifying the nonce for checking Admin Location Rules when ACF Field Group pages are loaded or various settings of the field group are modified. 
The `FILTER_SANITIZE_STRING` argument was deprecated in php 8.1
closes #69 
With ACF Pro v6.1.7, WPGraphQL 1.14.9 and WPGraphQL for ACF (v2.0.0-beta.3.1.0) active, when opening the admin page for an ACF Field Group:
The following error message would be displayed in the console in response to the AJAX method to check the graphql location rules: …

fix: replace `filter_input` with `sanitize_text_field`

---

composer.lock
src/assets/admin/js/main.js

This fixes a bug where a JS error occurs when Clone Fields are added to a field group
closes #76 
Trying to open the field settings of a clone field would trigger a JS error and the settings could not be edited. 
I can open the settings of a clone field without JS errors.

fix: js error when clone fields are added to a field group

---

src/FieldType/Taxonomy.php

Taxonomy field was returning null when field_type was set to return a single value (with select or radio button). By not returning null in case it is not an array (which is the default return when these field types are selected), it properly returns the term.
Also the type was being set to generic TermNode type, which did not allow to query custom fields inside these fields. By setting the type correctly to the taxonomy name it works properly
After changing these everything works as expected
(If it’s long, …

Fix TermNodes returning null when not array and fix type being set to generic TermNode in Taxonomy field

---

composer.json
composer.lock
phpstan.neon.dist
src/FieldConfig.php
src/FieldType/File.php
src/FieldType/Gallery.php
src/FieldType/Group.php
src/FieldType/Image.php
src/Registry.php
src/WPGraphQLAcf.php
tests/_support/WPUnit/AcfFieldTestCase.php
tests/_support/WPUnit/WPGraphQLAcfTestCase.php
tests/wpunit/FieldTypes/AcfeDateRangePickerFieldTest.php
tests/wpunit/FieldTypes/GroupFieldTest.php
tests/wpunit/FieldTypes/RepeaterFieldTest.php

This fixes some resolver issues with Repeater and Group field types when used on ACF Blocks. 
fixes #95 
I have a Group and Repeater field in a field group assigned to an ACF Block. 
The fields show in the Schema and I can query for them: 
On v2.0.0-beta.5.0.0, the group and repeater fields on a Block were resolving null values:
Now the Group and Repeater fields are resolving as expected

fix: repeater and group fields on ACF Blocks

---

composer.lock
src/Admin/PostTypeRegistration.php
src/Admin/TaxonomyRegistration.php
src/FieldConfig.php
src/FieldType/Relationship.php
src/FieldType/Repeater.php
tests/_support/WPUnit/AcfFieldTestCase.php
tests/_support/WPUnit/WPGraphQLAcfTestCase.php
tests/functional/CustomPostTypeRegistrationCest.php
tests/functional/CustomTaxonomyRegistrationCest.php
tests/wpunit/FieldTypes/RepeaterFieldTest.php

This PR fixes a bug where Post Types and Taxonomies imported from CPT UI weren't being fully respected by WPGraphQL for ACF. 
(Additionally, this fixes some incomplete tests lingering from #99)
closes #96 
Thanks to @mattgrshaw for help on this one! 🙌🏻

fix: bug with CPTUI imports

---

composer.lock
src/FieldConfig.php
src/FieldType/Gallery.php
src/FieldType/Repeater.php
src/LocationRules/LocationRules.php
src/assets/admin/js/main.js
tests/_support/WPUnit/AcfFieldTestCase.php
tests/_support/WPUnit/WPGraphQLAcfTestCase.php
tests/wpunit/FieldTypes/RepeaterFieldTest.php

This fixes a bug with that was causing "GraphQL Types" to not properly be set in response to ACF Field Group Location Changes.
closes #97 
closes #98
In the examples below, we can see the impact of changing GraphQL Locations on an ACF Field Group and how it affects the "GraphQL Types" the field group is associated with in the Graph
Changing locations didn't trigger GraphQL Types to update: 
Now changing locations properly updates GraphQL Types:

fix: #97 location mapping bugs

---

CHANGELOG.md
wp-graphql-acf.php

- [#102](https://github.com/wp-graphql/wpgraphql-acf/pull/102): fix: ACF Field Group Location Rules -> GraphQL Schema mapping bugs
- [#100](https://github.com/wp-graphql/wpgraphql-acf/pull/100): fix: bug with CPTUI Imports, post type/taxonomy graphql_single_name not being respected
- [#99](https://github.com/wp-graphql/wpgraphql-acf/pull/99): fix: Repeater, Group, File field not resolving properly when used as a field on ACF Blocks

release: v2.0.0-beta.5.1.0

---

src/FieldConfig.php
tests/wpunit/FieldTypes/OembedFieldTest.php
tests/wpunit/PostObjectFieldsTest.php

This updates the oEmbed field to return the results of `wp_oembed_get()` instead of returning the raw URL that was input to the field.
closes #106 
This is probably considered a breaking change to users that were previously getting the raw URL in response and doing something on the client with the url (i.e. fetching the oembed from the source, etc)
If needed, for users negatively impacted by this change, the `graphql_resolve_field` filter can be used to override the …

fix: oembed field type returns embed instead of URL entered to the field

---

src/Registry.php
src/WPGraphQLAcf.php

This fixes a bug with ACF Field Groups assigned to a Page Template not resolving correctly. 
closes #110 
The Field Group is queryable on the template, but the fields return `null`
The Field Group is queryable on the template, and the fields return expected values
The previous version of the plugin included this filter (see: https://github.com/wp-graphql/wp-graphql-acf/blob/develop/src/class-acf.php#L132-L144), but it wasn't properly ported over.

fix: #110 field groups on page templates not resolving

---

src/AcfGraphQLFieldType.php

Adds new filters to the AcfGraphQLFieldType class to help 3rd parties override default behaviors of mapping ACF Field Types to the Schema.
related: #104 
see: https://github.com/wp-graphql/wpgraphql-acf/issues/104#issuecomment-1796389341

feat: add pre filter for resolve type

---

.github/workflows/testing-integration.yml

Updates tests to run against WP 6.4
closes #121

ci: update tests to run against WordPress 6.4

---

CHANGELOG.md
src/FieldType/Relationship.php
wp-graphql-acf.php

- [#114](https://github.com/wp-graphql/wpgraphql-acf/pull/114): feat: add pre filter for resolve type
- [#111](https://github.com/wp-graphql/wpgraphql-acf/pull/111): fix: oembed field type returns embed instead of URL entered to the field
- [#112](https://github.com/wp-graphql/wpgraphql-acf/pull/112): fix: field groups on page templates not resolving
- [#116](https://github.com/wp-graphql/wpgraphql-acf/pull/116): fix: error when querying `post_object`, `relationship` or `page_link` field nested on a `repeater` or `flexible_content` field
- [#122](https://github.com/wp-graphql/wpgraphql-acf/pull/122): ci: update tests to run against WordPress 6.4

release: v2.0.0-beta.6.0.0

---

build/Updater.php
composer.json

WordPress.org isn't allowing plugins that include the Appsero Client SDK to be approved for hosting on WordPress.org due to code in the Updater.php class. (see: https://github.com/Appsero/client/issues/34)
This PR gets around that by replacing the Updater.php file with a blank Updater.php class during the plugin-build step
closes #129 
Ideally this is a temporary workaround as the Appsero team is working with WordPress.org on a more permanent solution

feat: replace Appsero Updater.php with blank class to pass .org req's

---

src/Model/AcfOptionsPage.php
src/Registry.php
src/Utils.php
tests/wpunit/OptionsPageTest.php

This fixes a bug where ACF Options Pages that are registered with a custom post_id were not resolving. 
closes #128 

fix: options page with custom post_id not resolving properly

---

composer.lock
src/AcfGraphQLFieldType.php
src/FieldConfig.php
src/FieldType/CloneField.php
src/FieldType/FlexibleContent.php
src/FieldType/Repeater.php
src/Registry.php
tests/_data/acf-export-clone-repeater.json
tests/_support/WPUnit/AcfFieldTestCase.php
tests/functional/AdminSettingsCest.php
tests/functional/TestCloneFieldsCest.php
tests/functional/TestCloneWithRepeaterCest.php

This fixes a bug where multiple clone fields using the "prefix_name" setting weren't being added to the Schema properly or resolving properly. 
Closes #125 
Given the following ACF Field Group export: 
[acf-export-2023-12-07.json.zip](https://github.com/wp-graphql/wpgraphql-acf/files/13606683/acf-export-2023-12-07.json.zip)
And a page with the following content entered using these fields: 
Inspecting the `CustomContent` Type in the Schema shows that it has 3 fields: 
- content: `String`
- sections: …

fix: clone fields not respecting prefix 

---

.github/workflows/deploy-to-wordpress.yml

A Github Worfklow should be added to the github repo that publishes the plugin to the repo after releases are tagged.
Right now, this job will fail, since we don't have the plugin at WP.org.

Build the plugin zip, deploy to WP

---

CHANGELOG.md
wp-graphql-acf.php

- [#136](https://github.com/wp-graphql/wpgraphql-acf/pull/136): fix: clone fields not respecting "prefix_name" setting
- [#126](https://github.com/wp-graphql/wpgraphql-acf/pull/126): fix: Make sure oembed field is also formatted when part of a flexible_content field. Thanks @kpoelhekke!
- [#131](https://github.com/wp-graphql/wpgraphql-acf/pull/131): ci: replace Appsero Updater.php with a blank class to satisfy WordPress.org reqs.
- [#132](https://github.com/wp-graphql/wpgraphql-acf/pull/132): fix: options page with custom post_id not resolving properly
- [#16](https://github.com/wp-graphql/wpgraphql-acf/pull/16): ci: Build the plugin zip, deploy to WordPress.org

release: v2.0.0 beta.7.0.0

---

src/FieldType/Taxonomy.php
src/FieldType/User.php
tests/wpunit/FieldTypes/TaxonomyFieldTest.php

This fixes a bug where the "taxonomy" field will return an error when queried if the field is set to not allow multiple selections, but has multiple selections stored. 
This can happen when the field was configured to allow multiple selections, had data saved, then is later changed to be a single select, but the stored data is still multiple values in an array. 
Related to #133 
1. Create a "Taxonomy" field on an ACF Field Group assigned to an ACF Block
2. Set the field to "Multi Select"
3. Edit the block using the field, selecting multiple terms
4. Save the …

fix: #133 taxonomy field on blocks

---

src/FieldType/User.php
tests/_support/WPUnit/AcfFieldTestCase.php
tests/_support/WPUnit/WPGraphQLAcfTestCase.php
tests/wpunit/FieldTypes/TextFieldTest.php
tests/wpunit/FieldTypes/UserFieldTest.php

Fixes a bug where the "user" field would return all public users when an array of IDs were stored as the meta value.
closes #162 
When saving specific users in a user field: 
Querying would return all publicly queryable users
Querying returns just the selected users

fix: user field returning all publicly queryable users

---

composer.lock
src/FieldType/Taxonomy.php
tests/wpunit/FieldTypes/TaxonomyFieldTest.php

fixes the sort order for querying fields of the taxonomy type.
closes #171 
Given a field of the "taxonomy" type set as a "multi select" and multiple terms stored:
Querying the field would return the nodes ordered by name
Querying the field returns the nodes in the same order they're saved

fix: taxonomy field resolves with wrong order

---

composer.lock
src/FieldType/Taxonomy.php
tests/wpunit/FieldTypes/TaxonomyFieldTest.php

When an ACF Field of the "Taxonomy" type field is set to store objects instead of IDs:
The resolver returns incorrect information. This resolves that by accounting for IDs or Objects being stored and returned.
closes #177 
(see issue #177 for the scenario)
With the following term saved in the "rubrique" field:
The "Uncategorized" term is resolved (not expected behavior)
The expected term is resolved:

fix: Taxonomy field returns incorrect data if set to store objects instead of IDs

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
composer.lock
readme.txt
src/FieldType/Taxonomy.php
tests/wpunit/FieldTypes/TaxonomyFieldTest.php
wpgraphql-acf.php

- [#178](https://github.com/wp-graphql/wpgraphql-acf/pull/178): fix: Taxonomy field returns incorrect data if set to store objects instead of IDs
- [#174](https://github.com/wp-graphql/wpgraphql-acf/pull/174): fix: taxonomy field resolves sorted in the incorrect order

release: v2.1.2

---

src/FieldConfig.php
src/FieldType/DatePicker.php
src/FieldType/DateTimePicker.php
src/FieldType/FlexibleContent.php
src/ThirdParty/AcfExtended/AcfExtended.php
tests/_support/WPUnit/AcfFieldTestCase.php

This updates the GraphQL field descriptions for fields of the DatePicker and DateTimePicker ACF field type to indicate that the strings returned will be formatted in RFC3339 format. 
This is helpful for client developers to know how they can expect to interact with the resulting value. 
closes #161 
In the WPGraphQL IDE we can see the field descriptions now include a link to the RFC3339 spec and a description that the field will return according to that spec.

feat: update docs Date fields to link to the RFC3339 spec 

---

src/Admin/PostTypeRegistration.php
src/Admin/TaxonomyRegistration.php

This updates the enqueue_admin_assets callback to expect a possible null value for the argument passed from `do_action( 'admin_enqueue_scripts' );`
closes #180

fix: admin_enqueue_scripts callback should expect a possible null value passed to it

---

src/FieldConfig.php
tests/wpunit/FieldTypes/GroupFieldTest.php

checks if the value is being passed down with the' __key' or the 'key' to better compensate for clone fields, specifically when groups are cloned
fixes #184 
fixes #151 
I believe this addresses the issues reported in #184 and #184 
Below are some before/after examples:
Following the reported steps to reproduce (see #184): 
Following the reported steps to reproduce (see #151):

fix: clone field within a group field type returns null values

---

wpgraphql-acf.php

https://make.wordpress.org/core/2024/03/05/introducing-plugin-dependencies-in-wordpress-6-5/

Add plugin dependency
